# Generated by Django 3.2.8 on 2021-10-31 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_pizza_topping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topik',
            new_name='topic',
        ),
    ]
